baseURL = 'https://yoshidev22.com/'
languageCode = 'es-mx'
title = 'Portfolio Yoshio Garcia'

[params]
  author = 'Yoshi'
  description = 'Portafolio de proyectos sobre ingeniería, sistemas de control, sistemas embebidos, robótica y desarrollo tecnológico general'