name: Deploy Hugo Site
on:
  push:
    branches: [ main ]

# Obliga a los despliegues a formarse en una fila para no saturar tu VPS
concurrency:
  group: deploy-vps

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar script en VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: /home/yoshi/Proyectos/deploy.sh